### ISSUE TITLE
MutualSelfAttentionControl中的qkv

### ISSUE THREAD

**Issue by chouchonkit** [TencentARC/MasaCtrl#12]
![image](https://github.com/TencentARC/MasaCtrl/assets/19634906/bee52cd2-e31e-4fe0-b3dc-d6df52c57976)

你好，我想请教一下为什么这边需要分开u, c各自计算再组合? 谢谢

**Comment by ljzycmd** [comment]
你好，这里u, c分别对应于unconditional 和conditional的部分，即对应于在使用classifier-free guidance的情况下的null prompt (或者negative prompt) 和给定的prompt的部分。
