### ISSUE TITLE
前景背景区分的语义Mask代码部分想问问是哪部分

### ISSUE THREAD

**Issue by hl123-123** [TencentARC/MasaCtrl#15]
![QQ截图20230520182516](https://github.com/TencentARC/MasaCtrl/assets/75974455/b6967c55-d5a6-485d-8fa8-4325716bf824)

 Mask-Guided Mutual Self-Attention中想问下就是Source Img 和Target Img各自的mask是怎么得到的，就是论文对应的代码是哪部分呢？
![QQ截图20230520185548](https://github.com/TencentARC/MasaCtrl/assets/75974455/c99acc62-1e35-4eda-afdb-7a8484f03300)

我的理解是这样masactrl_utils.py——》regiter_attention_editor_diffusers ——》ca_forward——》forward中 当使用Mutual Self-Attention时候(即target 参考source img 重建的feature)，q k v都是[4,img_feat_H*img_feat*W,feat_channels]，4应该是[source uncondition,target uncondition,source condition,target condion]。然后q k v通过map分别变成[4*8,img_feat_H*img_feat*W,feat_channels/8].输入到editor（MutualSelfAttentionControl）中。

再先进行chunk(2)，分别对于uncondition 和condition 通过attn_batch 实现 Mutual Self-Attention。

我不知道我这个理解对不对，若有错误，想请您指正一下。

关键我就找不到公式6 7 8中的SourceImg Mask和TargetImg Mask对应是怎么来的，又是怎么参与到Mutual Self-Attention中呢
![QQ截图20230520190819](https://github.com/TencentARC/MasaCtrl/assets/75974455/847392f5-b14c-454a-88e5-6a74aeb951a2)

谢谢！~

**Comment by ljzycmd** [comment]
Hi @hl123-123, 通过cross-attention map来提取mask的方法请参考https://github.com/TencentARC/MasaCtrl/blob/e537d1a50f4f57b5934163068bc889c6690981cc/masactrl/masactrl.py#LL145C7-L145C41。

此外，直接外部指定mask的方式也提供在了 https://github.com/TencentARC/MasaCtrl/blob/e537d1a50f4f57b5934163068bc889c6690981cc/masactrl/masactrl.py#L65。即可以先inference之后，通过segmentation的方法分割得到mask，然后在使用Mutual self-attention进行inference。

希望以上能够帮助到你~

**Comment by hl123-123** [comment]
> Hi @hl123-123, 通过cross-attention map来提取mask的方法请参考[https://github.com/TencentARC/MasaCtrl/blob/e537d1a50f4f57b5934163068bc889c6690981cc/masactrl/masactrl.py#LL145C7-L145C41。](https://github.com/TencentARC/MasaCtrl/blob/e537d1a50f4f57b5934163068bc889c6690981cc/masactrl/masactrl.py#LL145C7-L145C41%E3%80%82)
> 
> 此外，直接外部指定mask的方式也提供在了 [https://github.com/TencentARC/MasaCtrl/blob/e537d1a50f4f57b5934163068bc889c6690981cc/masactrl/masactrl.py#L65。即可以先inference之后，通过segmentation的方法分割得到mask，然后在使用Mutual](https://github.com/TencentARC/MasaCtrl/blob/e537d1a50f4f57b5934163068bc889c6690981cc/masactrl/masactrl.py#L65%E3%80%82%E5%8D%B3%E5%8F%AF%E4%BB%A5%E5%85%88inference%E4%B9%8B%E5%90%8E%EF%BC%8C%E9%80%9A%E8%BF%87segmentation%E7%9A%84%E6%96%B9%E6%B3%95%E5%88%86%E5%89%B2%E5%BE%97%E5%88%B0mask%EF%BC%8C%E7%84%B6%E5%90%8E%E5%9C%A8%E4%BD%BF%E7%94%A8Mutual) self-attention进行inference。
> 
> 希望以上能够帮助到你~

等等，您的意思是MutualSelfAttentionControl本身没有实现mask的功能，而是在MutualSelfAttentionControlMaskAuto和MutualSelfAttentionControlMask进行实现。谢谢

**Comment by ljzycmd** [comment]
对的对的。register function中的mask是继承了原始U-Net中原始的的实现过程，你可以在原始SD model中的U-Net实现中找到同样的代码。

**Comment by hl123-123** [comment]
> 对的对的。register function中的mask是继承了原始U-Net中原始的的实现过程，你可以在原始SD model中的U-Net实现中找到对应的代码。

谢谢，我下周再好好琢磨一下
