### ISSUE TITLE
关于MutualSelfAttentionControlMaskAuto的问题

### ISSUE THREAD

**Issue by LhaoH** [TencentARC/MasaCtrl#17]
您好！感谢你们伟大的工作！
目前我在尝试Mask引导编辑时存在一些问题，以编辑“A photo of a running corgi.”为例，以下是我编辑后的结果：
分别对应阈值为0.1,0.5,0.9
![图片](https://github.com/TencentARC/MasaCtrl/assets/50076227/2d8cb45a-6506-468b-9255-75456cadde22)
![图片](https://github.com/TencentARC/MasaCtrl/assets/50076227/05be7499-c939-4446-9785-5996e8364f4d)
![图片](https://github.com/TencentARC/MasaCtrl/assets/50076227/3b94e610-e95e-44de-b122-4e34044a56f6)
效果都不能与目标文本对齐，请问是我哪里出现问题了嘛？？您当时设置了哪些参数？以下是我的设置：
`# mask
editor = MutualSelfAttentionControlMaskAuto(start_step=STEP, start_layer=LAYPER, thres=0.9, mask_save_dir=out_dir)
regiter_attention_editor_diffusers(model, editor)`
另外请问分割后的图像，像论文里展示的mask图应该是在代码里哪一行？源码保存的是Attention图。
![图片](https://github.com/TencentARC/MasaCtrl/assets/50076227/6f33b94e-a142-4a78-bdaa-be2f59a5a8bd)

**Comment by ljzycmd** [comment]
你好，十分感谢对本项目的关注。MutualSelfAttentionControlMaskAuto需要指定前景对应的token idx，从而使用cross-attention map来提取得到对应的mask。所以针对你的prompt，可以设置如下: 
```python
MutualSelfAttentionControlMaskAuto(starting_step, starting_layer, thres=0.1, ref_token_idx=[1, 2], cur_token_idx=[5, 6])
```
![image](https://github.com/TencentARC/MasaCtrl/assets/15065356/f64d3b72-f5b7-404c-8d9c-4406e1a413a2)

而对于提取的mask图像，则可以在实例化editor的时候传入参数`mask_save_dir`来保存。相关代码如你的截图中所示。

希望可以帮助到你😄

**Comment by LhaoH** [comment]
@ljzycmd 请问一下这里的ref_token_idx、cur_token_idx是如何获得的？如果按照将目标prompt“A photo of a running corgi.”分词，最大的token索引是5才对，关于ref_token_idx、cur_token_idx分别代表的含义，在代码里的注释也不太理解。。
![图片](https://github.com/TencentARC/MasaCtrl/assets/50076227/fe919e32-ec92-4462-aac5-bba9ff11e795)

**Comment by ljzycmd** [comment]
你好，Tokenize过程会添加特殊token在句子的开头。可参考prompt-to-prompt中cross-attention map可视化。

**Comment by LhaoH** [comment]
@ljzycmd 谢谢您及时的回复！！这方面的我已经理解了！！  
 还有一个关于MutualSelfAttentionControlMask的问题：
这里我尝试简单生成原图和目标图的mask并指定，但是出错了，我主要利用之前生成的目标图获取其对应的mask，我的想法可能是错误的。
所以请问这里的mask_s和mask_t，您是怎么获取的？尤其关于这个mask_t的来源希望您可以重点讲解一下。
以下是我简单生成mask的代码：
```
def get_mask(image_path):
    image = cv2.imread(image_path)

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    blurred = cv2.GaussianBlur(gray, (5, 5), 0)

    _, thresh = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    mask = np.zeros_like(image)

    cv2.drawContours(mask, contours, -1, (255, 255, 255), -1)

    return mask
```
以及调用MutualSelfAttentionControlMask
```
# 外部指定mask
mask_s = get_mask('/data/zbdbc/project/sd-v2-finetune/MasaCtrl/input-folder/corgi.jpg')
mask_s = torch.from_numpy(mask_s)
mask_t = get_mask('/data/zbdbc/project/sd-v2-finetune/MasaCtrl/input-folder/masactrl_step4_layer10.png')
mask_t = torch.from_numpy(mask_t)

editor = MutualSelfAttentionControlMask(start_step=STEP, start_layer=LAYPER, mask_s=mask_s, mask_t=mask_t, mask_save_dir=out_dir)
regiter_attention_editor_diffusers(model, editor)
```

请原谅我提了很多的问题，我对你们的项目真的很感兴趣

**Comment by onevfall** [comment]
@ljzycmd 谢谢作者出色的工作和开源，但我依然没有完全弄清这里对于“A photo of a running corgi.”的提示，用ref_token_idx=[1, 2]和cur_token_idx=[5, 6]是对应什么？

> ```python
> MutualSelfAttentionControlMaskAuto(starting_step, starting_layer, thres=0.1, ref_token_idx=[1, 2], cur_token_idx=[5, 6])
> ```

![cross-attention_map](https://github.com/user-attachments/assets/a6c06ad3-8faf-4485-b65f-20ce1f31b1b1)

我按照你的提示，参考了prompt-to-prompt中cross-attention map可视化，猜测cur_token_idx=[5, 6]中，"5"是对应"running"，而"6"对应"corgi"，但我不清楚ref_token_idx=[1, 2]应该对应什么。希望能得到回复，非常感谢🙏

**Comment by ljzycmd** [comment]
> @ljzycmd 谢谢作者出色的工作和开源，但我依然没有完全弄清这里对于“A photo of a running corgi.”的提示，用ref_token_idx=[1, 2]和cur_token_idx=[5, 6]是对应什么？
> 
> > ```python
> > MutualSelfAttentionControlMaskAuto(starting_step, starting_layer, thres=0.1, ref_token_idx=[1, 2], cur_token_idx=[5, 6])
> > ```
> 
> ![cross-attention_map](https://private-user-images.githubusercontent.com/83062769/374644622-a6c06ad3-8faf-4485-b65f-20ce1f31b1b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjEwNDgsIm5iZiI6MTcyODUyMDc0OCwicGF0aCI6Ii84MzA2Mjc2OS8zNzQ2NDQ2MjItYTZjMDZhZDMtOGZhZi00NDg1LWI2NWYtMjBjZTFmMzFiMWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAwMzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMWI3MjVjOTYyODk3YzQzZThlOTE5MDM3NDYyYmRmN2QwZTBmYzc1ZDZhMzFlNzkzZTQ4ZTJkYTMxYzI4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rwlHAFKglEqXpGyAOt-m2oDDwPnrU4Av45kvD6lY0ZU)
> 
> 我按照你的提示，参考了prompt-to-prompt中cross-attention map可视化，猜测cur_token_idx=[5, 6]中，"5"是对应"running"，而"6"对应"corgi"，但我不清楚ref_token_idx=[1, 2]应该对应什么。希望能得到回复，非常感谢🙏

你好，感谢对本工作的兴趣。在对真实图像编辑过程中，因为我们把source prompt 设置为了 null，所以ref_token_idx 选取了靠前的 token 来表征图像中的主体内容。而对于 target_token_idx，选取和目标对应的 token 即可，故设置为了[5, 6] (对应running corgi)。

**Comment by onevfall** [comment]
@ljzycmd 感谢作者大大的回复！原来这里是真实图像的编辑，我理解这个案例了。

冒昧再咨询一个例子，以paper里framework图画的为例，source prompt="A photo of a dog"，target prompt=“A photo of a running dog”，此时ref_token_idx和target_token_idx应该是怎样的呢？

如果按"[startoftext] a photo of a dog [endoftext] [startoftext] a photo of a running dog [endoftext]"来思考，就是ref_token_idx为[5](对应dog），target_token_idx为[12, 13]（对应running dog），这是我的推导，不知道正确与否，恳请指正
