### ISSUE TITLE
发现一个非常奇怪的问题

### ISSUE THREAD

**Issue by zhangqizky** [TencentARC/MasaCtrl#18]
我在colab上运行的结果和在本地不一样。colab上效果应该是对的，虽然也不咋好（指的是没有论文中show的好）。
但是在本地，直接image_masactrl和image_ori是完全一样的结果，这是为什么啊？代码都是直接拉下来的啥也没改。这是我在本地跑的
all_step4_layer10.png
![image](https://github.com/TencentARC/MasaCtrl/assets/23207132/ec1d2f00-f0dc-46a5-b777-4583652711ec)

**Comment by ljzycmd** [comment]
你好，您安装的diffusers package不匹配，从而Attention injection的过程失败，请安装requirements.txt中的版本。
