### ISSUE TITLE
我想请问一个和您这个项目或许不那么相关的问题，关于图像重建

### ISSUE THREAD

**Issue by hl123-123** [TencentARC/MasaCtrl#19]
![QQ截图20230526234546](https://github.com/TencentARC/MasaCtrl/assets/75974455/ede6ef45-6c54-41d4-8af4-d7cad3e91323)
我一直很疑惑为啥我使用SD GUI中inpaint模式 非mask部分 可以重建的这么好，就连左上角的文字都清晰可见。它是直接把输入的图像非mask部分直接进行复制到最终图像上面吗，但是我又没有找到非mask区域信息直接复制的代码。我有点不太确定。

我也测试过直接使用AutoencoderKL将图像直接encode再decode，中间没有加噪和去噪，重建出来的图像也很明显与原图有差距。

那么将中间特征noise再denoise最后再decode得到的图像 我觉得 单从图像重建角度 生成的图像与原图偏差应该更大。

然后我想请问一下除了一般使用AutoencoderKL，还有其他的encoder吗。就是专门针对图像重建进行优化的encoder.

有encoder或者其他方式 可以做到完全几乎百分百的图像重建吗？

我之所以会问这个问题是因为我接触到了这样一个场景，希望可以给您带来思路：

这个场景是我去跨境电商公司和他们产品经理线下沟通得到的，他们确实也在做这方面。但是最大的问题就是货不对板。

在电商中，针对于一件衣服，比如T恤，我们 有它的产品图。传统我们需要请一个模特穿上这件衣服，得到模特图。因为人们都想看看真人穿这件衣服的效果嘛，可以很好的提升顾客下单意愿，因此模特图很重要。
然后有这么一家电子商务公司做衣服的有这么一个想法，请模特很贵，于是想通过AI直接输入衣服产品图输出模特图。但是模特图中模特穿的衣服必须和产品图百分之百一致。因为一旦不一致，哪怕仅仅一个袖口一个扣子不一致，都会出现货不对板的问题。这是很严重的问题。
然后您团队的这篇paper其实可以很有机会运用到这个场景中。通过让生成模特图的衣服MASK区域去参考 产品图衣服MASK的区域呢。毕竟产品图中的衣服占据了整张图的绝大部分。 但是可能有这几方面的一个顾虑：
1. 是否一张图像经过encode，中间denoise 再decode后生成 的图像和原图能一模一样呢？
2. 然后如果要把您这篇论文用在这个场景，那么target img为模特图。模特图中不仅仅是衣服还有模特这个人，相比source img只有衣服，target img这个人完全是多出来的。所有应该需要在target img 信息denoise的过程中使用mask，专门针对衣服区域去参考source img产品图的信息。可是真的针对于target img中间特征的针对衣服mask可以那么精准吗，可以专门针对于模特图中主体模特的衣服构建mask.
3. 当然source img重建的特征的mask应该可以直接使用通过事先将产品图衣服进行语义分割得到mask，然后缩放成中间特征大小作为 source img mask。因此主要难点应该是target img  的mask。
4. 另外其实针对于这个场景，source img可以不单单是一张图片而是 好几张图片。因为一个商家肯定有自己的衣服，商家可以不单单拍正面的图片 可以拍前后左右的。那么target img能不能不单单只参考一张图像的信息，而是参考一组图像的信息呢？

您这篇paper或许比较match以上这个值得商业化的领域，希望可以给您带来一些新的想法甚至是后续研究的思路。如果您愿意，我可以为您团队提供这方面的信息。因为我是电子商务的一名大三学生，虽然我学AI2年多了，主要用AI Studio。但是最多可以做到代码的理解和小的改进，一个人也很难做大的比较创新的探索在这方面。

谢谢您的阅读

**Comment by ljzycmd** [comment]
Hi @hl123-123, 回复稍晚，不好意思，以下是对你问题的一一解答：
1. SD inpaint 模式是直接进行mask blending的，所以背景其实就是原图的背景，不存在重建的问题。
2. 图像经过VAE encode并直接decode之后，不能做到100%的完全一致的重建，存在一定的差异，但是差役不大 (计算PSNR还是可以达到比较高的水平)。除了在自然图像上训练的VAE，还有在动漫图像上训练的，请参考Anything 的VAE。
3. 对于虚拟试衣任务而言，所提方法目前还做不到这么精细的控制，还需要进一步提升效果。

**Comment by hl123-123** [comment]
谢谢哥，目前衣服生成模特图 ，我看到比较好的解决方案是采用 把衣服套在假人模特上，然后给假人拍照，然后把衣服部分抠出来，进行其他部分的信息补全，做一个Inpaint(可参考https://www.zhihu.com/question/590884963?utm_id=0)，但是光影可能有点小问题。

但是另一个领域 或许我觉得真的很适合您这篇paper，给有声小说文字 配图片，或者给幼儿做相应的图画绘本（也是给每小段剧情配一张图片）。您这篇paper更好保证了，主角的外表不变，稍微有点小瑕疵其实问题不大。再加上lora训练一个大体的style，就不需要Lora专门保证人物不变了，而是把保证人物主体不变的压力给到了masactrl,这样一个Lora的复用性更高了，原先一个Lora只能做一个绘本，但是现在可以用来做一个系列的绘本（一个系列style一样），

**Comment by ljzycmd** [comment]
衣服这个，可以参考下这篇文章: https://github.com/johannakarras/DreamPose

对于你的第二点，看起来整体方案是可行的。

可通过邮件进行联系。

**Comment by hl123-123** [comment]
OK，等我把相关的整理一下再和您联系

**Comment by leeguandong** [comment]
masaCtrl还是qkv层面的工作，类似的工作还是比较多的，qkv层面的工作，大多是对文本对图像，或者图像对图像层面的对齐，因此对于qkv的设计可以做到主体一致或者风格转化类似的事情，小说推文这种场景还是有应用的。但对于tryon，masactrl是不够的，对于人台云台图生成的，目前主要还是inapinting，当然inpainting的方法有很多，masactrl也不是很适合。
