### ISSUE TITLE
论文中有个数学公式表达的错误

### ISSUE THREAD

**Issue by hl123-123** [TencentARC/MasaCtrl#2]
在3.1. Latent Diffusion Models中分母是不是少了个开根号
![12](https://user-images.githubusercontent.com/75974455/233010083-cf404f35-309a-4fba-b9a7-14b77b3e9881.jpg)

**Comment by ljzycmd** [comment]
您好，感谢你的仔细阅读并指出错误，我们会进行修改，并更新在后续的版本中。
