### ISSUE TITLE
请教cross-attention的一些问题

### ISSUE THREAD

**Issue by houjie8888** [TencentARC/MasaCtrl#27]
作者你好，这个工作太牛了。我有一些关于cross-attention的问题，希望得到您的回复~

1.请问一下LDM里面的cross-attention，为什么Q是空间投影特征，KV是文本投影特征呢。如果互换一下会怎么样呢，Q是文本特征，KV是空间特征这样。这个顺序在cross-attention里面有什么讲究吗。

2.此外，还想请教一下图4（b）的可视化是怎么做出来的呢，直接将projected Q喂到一个解码器还是用了其它什么工具呢？

**Comment by ljzycmd** [comment]
@houjie8888 你好，LDM的UNet中的cross-attention的作用是为了将文本信息作为条件encode到生成的过程中。而根据attention的公式可知，attention操作的本质是更具QK的关系对V进行聚合。故在该处需要将文本信息作为KV。而如果交换的话，文本信息则很难融合到图像的生成过程中，难以生成和文本匹配的结果。

图4（b）是对Query进行PCA分解，然后选取主要的3种成分作为RGB即可得到所示图片。

**Comment by houjie8888** [comment]
@ljzycmd 感谢~不知道是否方便提供一些相关的可视化代码呢~ (●ˇ∀ˇ●)

**Comment by ljzycmd** [comment]
@houjie8888, 你好，我将尽快把代码更新在此
