### ISSUE TITLE
令人惊叹的工作

### ISSUE THREAD

**Issue by hl123-123** [TencentARC/MasaCtrl#3]
昨天看了TencentARC的T2I-adapter ，用简单的外部适配器训练努力将SD可以被一般人有机会训练。今天又看到了您的团队这一杰出工作，可以很好的从一个独特的角度解决了图像自适应这一问题，不用微调，而是一种独特的角度的解构。嗯，又可以让一般人更好的 将SD模型进行控制，真的C

**Comment by ljzycmd** [comment]
Thank you for your attention. :blush:
