### ISSUE TITLE
How to determine the number of **CrossAttention** layers in a **StableDiffusion** model?

### ISSUE THREAD

**Issue by NuanBaobao** [TencentARC/MasaCtrl#46]
How to determine the number of **CrossAttention** layers in a **StableDiffusion** model. I noticed in the code that the number of CrossAttention layers in the SD model is stated to be 16:
```python
class MutualSelfAttentionControl(AttentionBase):
    MODEL_TYPE = {
        "SD": 16,
        "SDXL": 70
    }
```
However, in actual usage, I found that the number of CrossAttention layers is 32, with 12 layers in "down", 2 layers in "mid", and 18 layers in "up". How can this be understood?

```python
for net_name, net in model.unet.named_children():
    if "down" in net_name:
        down_cross_att_count += register_editor(net, 0, "down")
    elif "mid" in net_name:
        mid_cross_att_count += register_editor(net, 0, "mid")
    elif "up" in net_name:
        up_cross_att_count += register_editor(net, 0, "up")
editor.num_att_layers = down_cross_att_count + mid_cross_att_count + up_cross_att_count
```
In the **MutualSelfAttentionControl** class, the MODEL_TYPE dictionary is defined, which indicates the number of CrossAttention layers in different types of models. For the StableDiffusion (SD) model, the number of CrossAttention layers is set to 16; 

However, in actual usage, I found that the number of CrossAttention layers is 32, distributed as follows:
- The number of CrossAttention layers in the "down" (encoder) part is 12.
- The number of CrossAttention layers in the "mid" part is 2.
- The number of CrossAttention layers in the "up" (decoder) part is 18.

**Comment by ljzycmd** [comment]
Hi @NuanBaobao, thanks for your interest. Note that both self-attention and cross-attention layers are CrossAttention modules. Therefore, SD1.5 and SD1.4 have a total of 32 CrossAttention layers, 16 layers are self-attention, and the other 16 layers are cross-attention.

**Comment by LabShuHangGU** [comment]
I see, thank you very much for your explanation. I understand now. Best regards,

**Comment by NuanBaobao** [comment]
I understand now, thank you very much for your explanation. Best regards!
