### ISSUE TITLE
why need to change the shape of hidden states for similarity calculation?

### ISSUE THREAD

**Issue by parryppp** [TencentARC/MasaCtrl#47]
in masactrl_utils.py, line 100-110
<img width="460" alt="image" src="https://github.com/user-attachments/assets/542d7d1f-5650-49be-9e58-ac3e20faeba0">
I notice that the original shape of q is (2, 4096, 320), why change to (16, 4096, 40)

**Comment by ljzycmd** [comment]
Hi @parryppp, note that the Attention in the denoising is performed in a **multi-head** way. Thus the shape of the input tensor should be permuted.
