### ISSUE TITLE
confused about the implement of mutualselfattention

### ISSUE THREAD

**Issue by parryppp** [TencentARC/MasaCtrl#48]
<img width="515" alt="image" src="https://github.com/user-attachments/assets/e0d65888-25fa-41b2-b220-b4d3563c1ce3">
SORRY to bother you, I am stuck on the implementation of mutualselfattention, in the masactrl.py class MutualSelfAttentionControl, the forward function seems just split and implement the source attention and the target attention and then concatenate, how does the mutualselfattention QUERY from SOURCE KEY AND SOURCE VALUE?

**Comment by ljzycmd** [comment]
Hi @parryppp, note that in the new attention operation, `qu` is the unconditional part of both source and target images, while `ku[:num_heads]` and `vu[:num_heads]` are only from the source image. As a result, the target image can query source information from the source image.  The same goes for the conditional part. With such implementation, the source image reconstruction and target image editing processes are performed simultaneously.

**Comment by parryppp** [comment]
I appreciate your help, i am still a little confused about the meaning of qu, qc, ku, kc, vu, vc, could you clarify it for me? _qu is the unconditional part of both source and target images_, which means that _qc_ also contains information from the source image and the target image？So the _out_u_ and the _out_c_ both have the information from the source image and the target image, but according to your reply, the _out_c_ should only contain the information from the source image?

**Comment by ljzycmd** [comment]
Actually, `qu[:num_heads]` (with shape [num_heads, N, D]) is the query feature from the source image, and `qu[num_heads:]` (with shape [num_heads, N, D]) is the query feature from the target image. Thus, the output `out_u` is the concatenation of the attention outputs of the source and target images, with shape [2*num_heads, N, D]. 

You can validate the tensor shapes of the intermediate tensor variables for better understanding.

**Comment by parryppp** [comment]
Thanks for your suggestion, i am fresh to diffusion model, and i am still stuck on the meaning of feature qu[:num_heads]. I conduct a small experiment to verify it.
<img width="208" alt="image" src="https://github.com/user-attachments/assets/eb1d2d8b-ba9f-47a2-8c98-9c8a28638d95">
the tensor b with shape(2,3,4) (batch_size, N, dim), where 2 indicate 2 prompts(the source, the target),
and I permute the tensor shape into (4, 3, 2) for multi-head attention calculation, where the number of heads is 2,
<img width="209" alt="image" src="https://github.com/user-attachments/assets/bb878a50-d6d6-4f56-a1ae-deab24c77714">
<img width="216" alt="image" src="https://github.com/user-attachments/assets/4d349608-8668-4b7b-8daf-595c8a3500ae">
and I execute the chunk function, I got the following tensors,
<img width="103" alt="image" src="https://github.com/user-attachments/assets/18ab73a3-1443-4b18-b230-11e8d876b612">
in this case, the feature c1 is all from the source feature, c2 is all from the target feature, this result makes me so confused,  Could you help clarify? Thank you so much!

**Comment by ljzycmd** [comment]
Your toy experiment is correct. However, this is just the first step, the feature interaction is performed with the attention mechanism, and the target feature serves as the query feature, and the source feature serves as the key and value during the attention process. You can refer to the attention operation for more details.

**Comment by parryppp** [comment]
Thank you so much for your help!

**Comment by choidaedae** [comment]
this issue helps me a lot. thanks for your kindly explanation.
