### ISSUE TITLE
Will there google colab demo without webui? EDIT: I mean runpod or vast.ai

### ISSUE THREAD

**Issue by benagastov** [TencentARC/MasaCtrl#5]
We knew webui is banned in Google Colab. But it is said notebook with diffuser or using pro account is not banned. Since I always use Colab (EDIT: I mean runpod or vast.ai) will be there cloud demo? Huggingface space demo perhaps? I wish someone create extension for this. Thank you.

**Comment by ljzycmd** [comment]
Hi @benagastov, we released a gradio demo, and we will update a Colab demo later. 😃
