### ISSUE TITLE
Can’t reproduce the results in the paper

### ISSUE THREAD

**Issue by diyiiyiii** [TencentARC/MasaCtrl#7]
Hello, Thanks for you amazing work! I'm trying to reproduce results following “playground.ipynb”, but failed.  Could please tell me what I overlooked？
For example， when I try to edit "corgi.jpg" with and without masactrl, the results are same. And the dog's appearance has changed.
Thank you for your reply!

**Comment by ljzycmd** [comment]
Hello @diyiiyiii, according to your description, your environment may contain a mismatched version of the `Diffusers` package. You can check it. If this still cannot work, please let me know.

**Comment by g-jing** [comment]
I found similar issue. 
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/44223191/236384153-bba73c98-dfa8-4e90-83b8-522e94d33438.png">
The right two images should be fixed seed without MasaCtrl and fixed seed with MasaCtrl. But I did not find the difference

**Comment by diyiiyiii** [comment]
> > > Hello @diyiiyiii, according to your description, your environment may contain a mismatched version of the `Diffusers` package. You can check it. If this still cannot work, please let me know.
> > 
> > 
> > Thanks for your relpy! I reinstall the diffusers==0.3.0, but it still doesn't work. My torch version is 2.0.0+cu117.
> 
> Hi @diyiiyiii, you may upgrade the diffusers to version `0.15.0` as described in the requirement.txt. The attention register function `regiter_attention_editor_diffusers` will fail due to differences in the Attention layer's name between different diffusers versions.
Problem solved！Thanks very much！
