### ISSUE TITLE
加噪公式是不是也写错了？

### ISSUE THREAD

**Issue by hl123-123** [TencentARC/MasaCtrl#8]
![QQ截图20230506174613](https://user-images.githubusercontent.com/75974455/236616742-7d7ae31f-3b84-49d6-abaf-714e9559e788.jpg)
paper是好paper，就是稍微有点尴尬啊，好像对于扩散的数学公式不太熟悉的样子

**Comment by ljzycmd** [comment]
你好，这一块确实存在问题，后续版本会进行修正😃
